name: Compile LaTeX Resume
on: 
  push:
    tags:
      - "v*.*.*"
jobs:
  compile-resume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          latexmk_use_xelatex: true
          root_file: resume.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: Resume PDF
          path: resume.pdf
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: resume.pdf
      
    
